In [2]:
import pandas as pd
import numpy as np
import os
import pandas as pd
import numpy as np
import os
df = pd.read_csv('PhiUSIIL_Phishing_URL_Dataset.csv')
print("🔍 PhiUSIIL Dataset Loaded")
print(f"\nRows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
print("📋 Column Names:\n")
for i, column in enumerate(df.columns):
    print(f"{i + 1}. {column}")
print("🔎 First 5 Rows:\n")
display(df.head())
print("📐 Dataset Information:\n")
df.info()

🔍 PhiUSIIL Dataset Loaded

Rows: 196403
Columns: 55
📋 Column Names:

1. URL
2. URLLength
3. Domain
4. DomainLength
5. IsDomainIP
6. TLD
7. URLSimilarityIndex
8. CharContinuationRate
9. TLDLegitimateProb
10. URLCharProb
11. TLDLength
12. NoOfSubDomain
13. HasObfuscation
14. NoOfObfuscatedChar
15. ObfuscationRatio
16. NoOfLettersInURL
17. LetterRatioInURL
18. NoOfDegitsInURL
19. DegitRatioInURL
20. NoOfEqualsInURL
21. NoOfQMarkInURL
22. NoOfAmpersandInURL
23. NoOfOtherSpecialCharsInURL
24. SpacialCharRatioInURL
25. IsHTTPS
26. LineOfCode
27. LargestLineLength
28. HasTitle
29. Title
30. DomainTitleMatchScore
31. URLTitleMatchScore
32. HasFavicon
33. Robots
34. IsResponsive
35. NoOfURLRedirect
36. NoOfSelfRedirect
37. HasDescription
38. NoOfPopup
39. NoOfiFrame
40. HasExternalFormSubmit
41. HasSocialNet
42. HasSubmitButton
43. HasHiddenFields
44. HasPasswordField
45. Bank
46. Pay
47. Crypto
48. HasCopyrightInfo
49. NoOfImage
50. NoOfCSS
51. NoOfJS
52. NoOfSelfRef
53. NoOfEmptyRef
54. NoOfExternalRef
55. label
🔎 First 5 Rows:

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31.0,www.southbankmosaics.com,24.0,0.0,com,100.0,1.000000,0.522907,0.061933,...,0.0,0.0,1.0,34.0,20.0,28.0,119.0,0.0,124.0,1.0
1,https://www.uni-mainz.de,23.0,www.uni-mainz.de,16.0,0.0,de,100.0,0.666667,0.032650,0.050207,...,0.0,0.0,1.0,50.0,9.0,8.0,39.0,0.0,217.0,1.0
2,https://www.voicefmradio.co.uk,29.0,www.voicefmradio.co.uk,22.0,0.0,uk,100.0,0.866667,0.028555,0.064129,...,0.0,0.0,1.0,10.0,2.0,7.0,42.0,2.0,5.0,1.0
3,https://www.sfnmjournal.com,26.0,www.sfnmjournal.com,19.0,0.0,com,100.0,1.000000,0.522907,0.057606,...,1.0,1.0,1.0,3.0,27.0,15.0,22.0,1.0,31.0,1.0
4,https://www.rewildingargentina.org,33.0,www.rewildingargentina.org,26.0,0.0,org,100.0,1.000000,0.079963,0.059441,...,1.0,0.0,1.0,244.0,15.0,34.0,72.0,1.0,85.0,1.0

📐 Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196403 entries, 0 to 196402
Data columns (total 55 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   URL                         196403 non-null  object
 1   URLLength                   196402 non-null  float64
 2   Domain                      196402 non-null  object
 3   DomainLength                196402 non-null  float64
 4   IsDomainIP                  196402 non-null  float64
 5   TLD                         196402 non-null  object
 6   URLSimilarityIndex          196402 non-null  float64
 7   CharContinuationRate        196402 non-null  float64
 8   TLDLegitimateProb           196402 non-null  float64
 9   URLCharProb                 196402 non-null  float64
 10  TLDLength                   196402 non-null  float64
 11  NoOfSubDomain               196402 non-null  float64
 12  HasObfuscation              196402 non-null  float64
 13  NoOfObfuscatedChar          196402 non-null  float64
 14  ObfuscationRatio            196402 non-null  float64
 15  NoOfLettersInURL            196402 non-null  float64
 16  LetterRatioInURL            196402 non-null  float64
 17  NoOfDegitsInURL             196402 non-null  float64
 18  DegitRatioInURL             196402 non-null  float64
 19  NoOfEqualsInURL             196402 non-null  float64
 20  NoOfQMarkInURL              196402 non-null  float64
 21  NoOfAmpersandInURL          196402 non-null  float64
 22  NoOfOtherSpecialCharsInURL  196402 non-null  float64
 23  SpacialCharRatioInURL       196402 non-null  float64
 24  IsHTTPS                     196402 non-null  float64
 25  LineOfCode                  196402 non-null  float64
 26  LargestLineLength           196402 non-null  float64
 27  HasTitle                    196402 non-null  float64
 28  Title                       196402 non-null  object
 29  DomainTitleMatchScore       196402 non-null  float64
 30  URLTitleMatchScore          196402 non-null  float64
 31  HasFavicon                  196402 non-null  float64
 32  Robots                      196402 non-null  float64
 33  IsResponsive                196402 non-null  float64
 34  NoOfURLRedirect             196402 non-null  float64
 35  NoOfSelfRedirect            196402 non-null  float64
 36  HasDescription              196402 non-null  float64
 37  NoOfPopup                   196402 non-null  float64
 38  NoOfiFrame                  196402 non-null  float64
 39  HasExternalFormSubmit       196402 non-null  float64
 40  HasSocialNet                196402 non-null  float64
 41  HasSubmitButton             196402 non-null  float64
 42  HasHiddenFields             196402 non-null  float64
 43  HasPasswordField            196402 non-null  float64
 44  Bank                        196402 non-null  float64
 45  Pay                         196402 non-null  float64
 46  Crypto                      196402 non-null  float64
 47  HasCopyrightInfo            196402 non-null  float64
 48  NoOfImage                   196402 non-null  float64
 49  NoOfCSS                     196402 non-null  float64
 50  NoOfJS                      196402 non-null  float64
 51  NoOfSelfRef                 196402 non-null  float64
 52  NoOfEmptyRef                196402 non-null  float64
 53  NoOfExternalRef             196402 non-null  float64
 54  label                       196402 non-null  float64
dtypes: float64(51), object(4)
memory usage: 82.4+ MB

In [3]:
print("🎯 Label Distribution:\n")

label_counts = df['label'].value_counts()

print(label_counts)

print("\n📊 Label Percentage:\n")

label_percentage = (
    df['label']
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(label_percentage)
print("❓ Missing Values:\n")

missing_values = df.isnull().sum()

missing_values = missing_values[missing_values > 0]

if len(missing_values) == 0:
    print("No missing values found.")
else:
    print(missing_values)

print(
    f"\nTotal missing values: "
    f"{df.isnull().sum().sum()}"
)
print("❓ Missing Values:\n")

missing_values = df.isnull().sum()

missing_values = missing_values[missing_values > 0]

if len(missing_values) == 0:
    print("No missing values found.")
else:
    print(missing_values)

print(
    f"\nTotal missing values: "
    f"{df.isnull().sum().sum()}"
)

🎯 Label Distribution:

label
1.0    112436
0.0     83966
Name: count, dtype: int64

📊 Label Percentage:

label
1.0    57.25
0.0    42.75
Name: proportion, dtype: float64
❓ Missing Values:

URLLength                     1
Domain                        1
DomainLength                  1
IsDomainIP                    1
TLD                           1
URLSimilarityIndex            1
CharContinuationRate          1
TLDLegitimateProb             1
URLCharProb                   1
TLDLength                     1
NoOfSubDomain                 1
HasObfuscation                1
NoOfObfuscatedChar            1
ObfuscationRatio              1
NoOfLettersInURL              1
LetterRatioInURL              1
NoOfDegitsInURL               1
DegitRatioInURL               1
NoOfEqualsInURL               1
NoOfQMarkInURL                1
NoOfAmpersandInURL            1
NoOfOtherSpecialCharsInURL    1
SpacialCharRatioInURL         1
IsHTTPS                       1
LineOfCode                    1
LargestLineLength             1
HasTitle                      1
Title                         1
DomainTitleMatchScore         1
URLTitleMatchScore            1
HasFavicon                    1
Robots                        1
IsResponsive                  1
NoOfURLRedirect               1
NoOfSelfRedirect              1
HasDescription                1
NoOfPopup                     1
NoOfiFrame                    1
HasExternalFormSubmit         1
HasSocialNet                  1
HasSubmitButton               1
HasHiddenFields               1
HasPasswordField              1
Bank                          1
Pay                           1
Crypto                        1
HasCopyrightInfo              1
NoOfImage                     1
NoOfCSS                       1
NoOfJS                        1
NoOfSelfRef                   1
NoOfEmptyRef                  1
NoOfExternalRef               1
label                         1
dtype: int64

Total missing values: 54
❓ Missing Values:

URLLength                     1
Domain                        1
DomainLength                  1
IsDomainIP                    1
TLD                           1
URLSimilarityIndex            1
CharContinuationRate          1
TLDLegitimateProb             1
URLCharProb                   1
TLDLength                     1
NoOfSubDomain                 1
HasObfuscation                1
NoOfObfuscatedChar            1
ObfuscationRatio              1
NoOfLettersInURL              1
LetterRatioInURL              1
NoOfDegitsInURL               1
DegitRatioInURL               1
NoOfEqualsInURL               1
NoOfQMarkInURL                1
NoOfAmpersandInURL            1
NoOfOtherSpecialCharsInURL    1
SpacialCharRatioInURL         1
IsHTTPS                       1
LineOfCode                    1
LargestLineLength             1
HasTitle                      1
Title                         1
DomainTitleMatchScore         1
URLTitleMatchScore            1
HasFavicon                    1
Robots                        1
IsResponsive                  1
NoOfURLRedirect               1
NoOfSelfRedirect              1
HasDescription                1
NoOfPopup                     1
NoOfiFrame                    1
HasExternalFormSubmit         1
HasSocialNet                  1
HasSubmitButton               1
HasHiddenFields               1
HasPasswordField              1
Bank                          1
Pay                           1
Crypto                        1
HasCopyrightInfo              1
NoOfImage                     1
NoOfCSS                       1
NoOfJS                        1
NoOfSelfRef                   1
NoOfEmptyRef                  1
NoOfExternalRef               1
label                         1
dtype: int64

Total missing values: 54

In [4]:
print("=" * 50)
print("🧹 STEP 2: DATA CLEANING")
print("=" * 50)

# Convert URL to string
df['URL'] = df['URL'].astype(str)

# Remove leading and trailing spaces
df['URL'] = df['URL'].str.strip()

# Remove trailing slash
df['URL'] = df['URL'].str.rstrip('/')

print("✅ URL formatting cleaned")
before_duplicates = len(df)

df = df.drop_duplicates(
    subset=['URL']
).reset_index(drop=True)

after_duplicates = len(df)

duplicates_removed = (
    before_duplicates - after_duplicates
)

print(f"Rows before duplicate removal: {before_duplicates}")
print(f"Rows after duplicate removal:  {after_duplicates}")
print(f"Duplicate URLs removed:        {duplicates_removed}")
before_missing = len(df)

df = df.dropna().reset_index(drop=True)

after_missing = len(df)

missing_rows_removed = (
    before_missing - after_missing
)

print(f"Rows before removing missing values: {before_missing}")
print(f"Rows after removing missing values:  {after_missing}")
print(f"Rows removed:                        {missing_rows_removed}")
print("=" * 50)
print("📊 FINAL CLEANED DATASET")
print("=" * 50)

print(f"\nRows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print(
    f"\nTotal missing values: "
    f"{df.isnull().sum().sum()}"
)

print(
    f"Duplicate URLs: "
    f"{df.duplicated(subset=['URL']).sum()}"
)

print("\n🎯 Label Distribution:")
print(df['label'].value_counts())

print("\n🔎 First 5 Cleaned Rows:")
display(df.head())
CLEANED_FILE = 'phiusiil_cleaned.csv'

df.to_csv(
    CLEANED_FILE,
    index=False
)

print(f"✅ Cleaned dataset saved as: {CLEANED_FILE}")
from google.colab import files

files.download('phiusiil_cleaned.csv')

==================================================
🧹 STEP 2: DATA CLEANING
==================================================
✅ URL formatting cleaned
Rows before duplicate removal: 196403
Rows after duplicate removal:  195341
Duplicate URLs removed:        1062
Rows before removing missing values: 195341
Rows after removing missing values:  195340
Rows removed:                        1
==================================================
📊 FINAL CLEANED DATASET
==================================================

Rows: 195340
Columns: 55

Total missing values: 0
Duplicate URLs: 0

🎯 Label Distribution:
label
1.0    112435
0.0     82905
Name: count, dtype: int64

🔎 First 5 Cleaned Rows:

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31.0,www.southbankmosaics.com,24.0,0.0,com,100.0,1.000000,0.522907,0.061933,...,0.0,0.0,1.0,34.0,20.0,28.0,119.0,0.0,124.0,1.0
1,https://www.uni-mainz.de,23.0,www.uni-mainz.de,16.0,0.0,de,100.0,0.666667,0.032650,0.050207,...,0.0,0.0,1.0,50.0,9.0,8.0,39.0,0.0,217.0,1.0
2,https://www.voicefmradio.co.uk,29.0,www.voicefmradio.co.uk,22.0,0.0,uk,100.0,0.866667,0.028555,0.064129,...,0.0,0.0,1.0,10.0,2.0,7.0,42.0,2.0,5.0,1.0
3,https://www.sfnmjournal.com,26.0,www.sfnmjournal.com,19.0,0.0,com,100.0,1.000000,0.522907,0.057606,...,1.0,1.0,1.0,3.0,27.0,15.0,22.0,1.0,31.0,1.0
4,https://www.rewildingargentina.org,33.0,www.rewildingargentina.org,26.0,0.0,org,100.0,1.000000,0.079963,0.059441,...,1.0,0.0,1.0,244.0,15.0,34.0,72.0,1.0,85.0,1.0

✅ Cleaned dataset saved as: phiusiil_cleaned.csv